name:  GitVersion Workflow

on:
  push:
    branches:
      - '**'
    
jobs:
  calculate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: '6.4.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v4.1.0
    